# reference https://github.com/jkeylu/deploy-hexo-site-by-travis-ci
language: node_js
branches:
  only:
  - master
before_install:
- npm install hexo-cli -g
install:
- npm i
before_script:
- git config --global user.name 'wayou'
- git config --global user.email 'liuwayong@gmail.com'
script:
- hexo g
after_success:
- mkdir .deploy
- cd .deploy
- git clone --depth 1 --branch gh-pages --single-branch $GH_TOKEN . || (git init && git remote add -t gh-pages origin $GH_TOKEN)
- rm -rf ./*
- cp -r ../public/* .
- git add -A .
- git commit -m 'Auto Update from TRAVIS-CI'
- git branch -m gh-pages
- git push -q $GH_TOKEN HEAD:gh-pages
